name: Build CoyoteWOLtool SPK

on:
  push:
    branches: [ main ] # Se déclenche à chaque push sur la branche 'main'
  workflow_dispatch: # Permet de lancer la compilation manuellement

jobs:
  build:
    runs-on: ubuntu-latest # Utilise un environnement Linux standard

    steps:
      # Étape 1: Cloner l'environnement de compilation ET le projet lui-même
      # Cette méthode est plus robuste que d'utiliser actions/checkout
      - name: Clone spksrc and project repository
        run: |
          git clone https://github.com/SynoCommunity/spksrc.git /tmp/spksrc
          git clone https://github.com/${{ github.repository }}.git /tmp/project
          
      # Étape 2: Préparer les fichiers pour la compilation
      - name: Prepare build environment
        run: |
          mkdir -p /tmp/spksrc/spk/CoyoteWOLtool
          cp -a /tmp/project/* /tmp/spksrc/spk/CoyoteWOLtool/

      # Étape 3: Lancer la compilation
      - name: Build the package
        run: make -C /tmp/spksrc/spk/CoyoteWOLtool arch-noarch

      # Étape 4: Téléverser le paquet .spk compilé comme un "artefact"
      - name: Upload SPK artifact
        uses: actions/upload-artifact@v4
        with:
          name: CoyoteWOLtool-spk
          path: /tmp/spksrc/packages/*.spk
