# Rôle : Automatise la création du paquet .spk.
# MISE À JOUR : Utilise la version v4 de upload-artifact et déclenchement manuel.
name: Build Synology SPK Package (Manual)

on:
  workflow_dispatch: # Permet de lancer manuellement le build depuis l'interface GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y fakeroot

      - name: Vendor Python dependencies
        run: |
          pip install --upgrade pip
          mkdir -p src/vendor
          # Télécharge les bibliothèques dans le dossier 'vendor'
          pip install --platform manylinux1_x86_64 --target=src/vendor --implementation cp --python-version 3.9 --only-binary=:all: --upgrade Flask gunicorn scapy

      - name: Build the SPK package
        run: |
          # Crée la structure des répertoires pour le paquet
          mkdir -p build/package
          cp -r src/* build/package/
          cp -r scripts/* build/package/
          cp INFO build/package/
          cp LICENSE build/package/
          mkdir -p build/package/ui
          cp src/frontend/index.html build/package/ui/
          
          # Copie les icônes pour l'assistant d'installation de DSM
          mkdir -p build/package/WIZARD_UIFILES
          cp assets/Icon.png build/package/WIZARD_UIFILES/PACKAGE_ICON.PNG
          cp assets/Icon-72.png build/package/WIZARD_UIFILES/PACKAGE_ICON_72.PNG
          
          # Crée l'archive .tgz contenant les fichiers du paquet
          cd build/package
          tar -czf ../package.tgz *
          cd ../..

          # Crée le paquet final .spk
          tar -cvf Coyote-WOL-tool.spk -C build package.tgz

      - name: Upload SPK artifact
        uses: actions/upload-artifact@v4 # <-- MISE À JOUR ICI
        with:
          name: Coyote-WOL-tool-spk
          path: Coyote-WOL-tool.spk
