- name: Build the SPK package
        run: |
          # 1. Créer le répertoire pour le contenu de l'application (le "payload")
          mkdir -p payload
          cp -r src/* payload/
          cp LICENSE payload/

          # 2. Créer l'archive package.tgz SANS forcer l'owner à root
          tar -czf package.tgz -C payload .

          # 3. Créer la structure racine du paquet .spk
          mkdir -p spk_root/WIZARD_UIFILES
          mv package.tgz spk_root/
          cp INFO spk_root/
          cp -r conf spk_root/
          cp -r scripts spk_root/
          cp assets/Icon.png spk_root/WIZARD_UIFILES/PACKAGE_ICON.PNG
          cp assets/Icon-72.png spk_root/WIZARD_UIFILES/PACKAGE_ICON_72.PNG

          # 4. Créer le fichier .spk final SANS fakeroot
          cd spk_root
          tar -cvf ../Coyote-WOL-tool.spk *
          cd ..
